### ISSUE TITLE
Modify an image in cache

### ISSUE THREAD

**Issue by jpambrun** [chafey/cornerstone#11]
I'm tying to enable the streaming of pixel data as they are needed to decrease initial loading times and and increase productivity. 

In order do this, I need to be able to update an image that is already in the cache. Would you be open to accept a pull request adding :

* an updateImagePromise(imageId, imagePromise) function to imageCache.js;
* an registerImageUpdater(scheme, imageUpdater) and updateImage(imageId, privateData) to imageLoader.js ? 

Can you imagine a better alternative? I understand that adding such a small and peculiar feature is cumbersome; I would understand if were to refuse because you didn't want to support this feature after the initial pull request.

**Comment by chafey** [comment]
Hi jpambrun,

I actually need this functionality for my own streaming mechanism so am OK with such a change.  I don't understand the design you are proposing so feel free to explain more or submit a pull request if you already implemented.  Do you see anything wrong with just adding a updateImageSize(imageId, imageSize) function to imageCache.js that updates cachedImage.sizeInBytes?

**Comment by jpambrun** [comment]
I was trying to keep the same philosophy used by the image loader. I would 

1. Register an image updater along side my image loader.
2. In the application code, updateImage(imageId, privateData) from imageLoader.js would be called as required to increase quality. This function would then :
   * call the registered image updater passing the privateData object that may contain the newly required resolution, ROI,  quality, etc.;
   *  call cornerstone.imageCache.updateImagePromise(imageId, imagePromise) to update the cachedImage object;
   * return the imagePromisse just like loadAndCacheImage(..) does.

**Comment by chafey** [comment]
I am not sure if cornerstone core needs to provide any support beyond adjusting the cache size for an image.  The actual updating logic (including the imageUpdater concept you propose) can probably be in the image loader itself.  This is how I implemented it for my streaming mechanism at least.  Perhaps I am missing something though - have you implemented the image updater mechanism yet?  If so, can you provide a link for me to review?

**Comment by jpambrun** [comment]
So far I have this, but it is not done yet:

https://github.com/jpambrun/cornerstone/tree/feat-updateImageInCache

It's just that I figured that the imageCache functions and datastructures should not be application facing APIs. Same thing goes for the imageLoaders. However, the application needs to be able to tell the cornerstone framework when and what new data is required. 

Perhaps the difference is that you want to continually stream new data from the initial request until the data is completely downloaded (i.e. data driven). On the other hand, what I want to do is load more data if the user zooms or if he inspect a slice from a stack for more than x sec (i.e. user driven).

**Comment by jpambrun** [comment]
I still don't understand how you did it. The imagePromise can only be resolved once. How do you tell the application that the image was updated? Keep in mind that I'm still new to javascript and I'm still struggling a bit with this very async way of doing everything.

**Comment by leonardorame** [comment]
Hi @jpambrun, please correct me if I'm wrong, your idea is to first load a very low resolution of the image, then an improved version and finally the high res version?.

Do you have an example of streaming a large image, like an MG for example?. I'm also interested in this feature.

**Comment by swederik** [comment]
Hey @leonardorame, he did a demo of it here: http://jpambrun.github.io/ but with a stack of 512x512 images.

In order to prepare images that will work with the demo, you need to write your image as a .raw file (I used 16 bit integers, must be big endian for OpenJPEG!), then you can use OpenJPEG's opj_compress to compress it into a jp2 file. Then I used gdcmimg to encaspsulate this into a dcm file. Finally I used a python script using pydicom to add the private tags necessary for the progressive stream / display.

It works pretty well when the images are processed, but the major drawback is that the initial compression time is quite long. It can also be tricky to figure out how many web workers should be spawned. Eventually I gave up for now, but maybe Jean Francois is still working on it.

**Comment by malaterre** [comment]
@swederik Please read `gdcmimg` manual. For instance: [gdcmimg warnings](http://gdcm.sourceforge.net/2.6/html/gdcmimg.html#warning) You should not encapsulated JP2 since it will contains the JP2 header, instead encapsulate a J2K.

**Comment by swederik** [comment]
Yep you're right, checking back I did use j2k and just explained it incorrectly. Thanks for the correction!

**Comment by jpambrun** [comment]
Unfortunately, the js decoder is currently too slow to be realistically
used with large images. It works great with large stacks because each slice
can be decoded in parallel.

Using tiles on large images could enable parallel decoding without
significant changes to the decoder, but may cause visible artifacts at tile
junctions when used in lossly mode.
I don't know how complicated it would be to add parallelism on a more
granular level with the current implementation.

Maybe it is a good time to retry Emscripten + OpenJpeg and compare
performances.

**Comment by chafey** [comment]
Latest code now has a function changeImageIdCacheSize() which lets you notify the cache that the the size of the image has changed.  Will that work for you?

**Comment by chafey** [comment]
Ping @jpambrun - can you check?

**Comment by jpambrun** [comment]
Sorry Chris, I am still here, just very busy. Hopefully, I will be able to look at this in the near future. I will close this issue in the meantime. Thanks.
